/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as RespRouteImport } from './routes/_resp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResponsavelLoginRouteImport } from './routes/responsavel-login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AppAdmRouteImport } from './routes/_app.adm'
import { Route as AppChefiaRouteImport } from './routes/_app.chefia'
import { Route as AppPainelSetorRouteImport } from './routes/_app.painel-setor'
import { Route as RespResponsavelRouteImport } from './routes/_resp.responsavel'
import { Route as AppAdmIndexRouteImport } from './routes/_app.adm.index'
import { Route as AppAdmAuditoriaRouteImport } from './routes/_app.adm.auditoria'
import { Route as AppAdmBaseRouteImport } from './routes/_app.adm.base'
import { Route as AppAdmBuscarRouteImport } from './routes/_app.adm.buscar'
import { Route as AppAdmBuscasRouteImport } from './routes/_app.adm.buscas'
import { Route as AppAdmConfiguracoesRouteImport } from './routes/_app.adm.configuracoes'
import { Route as AppAdmEtiquetaRouteImport } from './routes/_app.adm.etiqueta'
import { Route as AppAdmExplorarRouteImport } from './routes/_app.adm.explorar'
import { Route as AppAdmIaRouteImport } from './routes/_app.adm.ia'
import { Route as AppAdmIntegracoesRouteImport } from './routes/_app.adm.integracoes'
import { Route as AppAdmNotificacoesRouteImport } from './routes/_app.adm.notificacoes'
import { Route as AppAdmPainelEmailsRouteImport } from './routes/_app.adm.painel-emails'
import { Route as AppAdmRelatoriosRouteImport } from './routes/_app.adm.relatorios'
import { Route as AppInventarioConferenciaRouteImport } from './routes/_app.inventario.conferencia'
import { Route as AppInventarioListaRouteImport } from './routes/_app.inventario.lista'
import { Route as AppInventarioTransferirRouteImport } from './routes/_app.inventario.transferir'
import { Route as AppLocaisBensSetorRouteImport } from './routes/_app.locais.bens-setor'
import { Route as RespResponsavelAvaliacaoRouteImport } from './routes/_resp.responsavel.avaliacao'
import { Route as RespResponsavelInventarioRouteImport } from './routes/_resp.responsavel.inventario'
import { Route as RespResponsavelPortariaRouteImport } from './routes/_resp.responsavel.portaria'
import { Route as RespResponsavelTransferenciaRouteImport } from './routes/_resp.responsavel.transferencia'
import { Route as RespResponsavelTransferenciasPendentesRouteImport } from './routes/_resp.responsavel.transferencias-pendentes'
import { Route as RespResponsavelTrocaResponsabilidadeRouteImport } from './routes/_resp.responsavel.troca-responsabilidade'
import { Route as RespResponsavelTutorialRouteImport } from './routes/_resp.responsavel.tutorial'
import { Route as AppAdmBensCadastroRouteImport } from './routes/_app.adm.bens.cadastro'
import { Route as AppAdmBensCategoriasRouteImport } from './routes/_app.adm.bens.categorias'
import { Route as AppAdmContabilidadeUsuariosRouteImport } from './routes/_app.adm.contabilidade.usuarios'
import { Route as AppAdmFotosCanvasRouteImport } from './routes/_app.adm.fotos.canvas'
import { Route as AppAdmFotosCapturarRouteImport } from './routes/_app.adm.fotos.capturar'
import { Route as AppAdmGalpaoEmpenhosRouteImport } from './routes/_app.adm.galpao.empenhos'
import { Route as AppAdmGalpaoGraficosRouteImport } from './routes/_app.adm.galpao.graficos'
import { Route as AppAdmGalpaoRetiradasRouteImport } from './routes/_app.adm.galpao.retiradas'
import { Route as AppAdmInventarioMerendaRouteImport } from './routes/_app.adm.inventario.merenda'
import { Route as AppAdmInventarioMonitoramentoRouteImport } from './routes/_app.adm.inventario.monitoramento'
import { Route as AppAdmInventarioTransferenciasRouteImport } from './routes/_app.adm.inventario.transferencias'
import { Route as AppAdmLocaisCadastroUsuariosRouteImport } from './routes/_app.adm.locais.cadastro-usuarios'
import { Route as AppAdmLocaisFichasRouteImport } from './routes/_app.adm.locais.fichas'
import { Route as AppAdmLocaisPortariaRouteImport } from './routes/_app.adm.locais.portaria'
import { Route as AppAdmGalpaoRetiradasGerenciarRouteImport } from './routes/_app.adm.galpao.retiradas.gerenciar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const RespRoute = RespRouteImport.update({
  id: '/_resp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsavelLoginRoute = ResponsavelLoginRouteImport.update({
  id: '/responsavel-login',
  path: '/responsavel-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdmRoute = AppAdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => AppRoute,
} as any)
const AppChefiaRoute = AppChefiaRouteImport.update({
  id: '/chefia',
  path: '/chefia',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelSetorRoute = AppPainelSetorRouteImport.update({
  id: '/painel-setor',
  path: '/painel-setor',
  getParentRoute: () => AppRoute,
} as any)
const RespResponsavelRoute = RespResponsavelRouteImport.update({
  id: '/responsavel',
  path: '/responsavel',
  getParentRoute: () => RespRoute,
} as any)
const AppAdmIndexRoute = AppAdmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmAuditoriaRoute = AppAdmAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmBaseRoute = AppAdmBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmBuscarRoute = AppAdmBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmBuscasRoute = AppAdmBuscasRouteImport.update({
  id: '/buscas',
  path: '/buscas',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmConfiguracoesRoute = AppAdmConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmEtiquetaRoute = AppAdmEtiquetaRouteImport.update({
  id: '/etiqueta',
  path: '/etiqueta',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmExplorarRoute = AppAdmExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmIaRoute = AppAdmIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmIntegracoesRoute = AppAdmIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmNotificacoesRoute = AppAdmNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmPainelEmailsRoute = AppAdmPainelEmailsRouteImport.update({
  id: '/painel-emails',
  path: '/painel-emails',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmRelatoriosRoute = AppAdmRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppInventarioConferenciaRoute =
  AppInventarioConferenciaRouteImport.update({
    id: '/inventario/conferencia',
    path: '/inventario/conferencia',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventarioListaRoute = AppInventarioListaRouteImport.update({
  id: '/inventario/lista',
  path: '/inventario/lista',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioTransferirRoute = AppInventarioTransferirRouteImport.update({
  id: '/inventario/transferir',
  path: '/inventario/transferir',
  getParentRoute: () => AppRoute,
} as any)
const AppLocaisBensSetorRoute = AppLocaisBensSetorRouteImport.update({
  id: '/locais/bens-setor',
  path: '/locais/bens-setor',
  getParentRoute: () => AppRoute,
} as any)
const RespResponsavelAvaliacaoRoute =
  RespResponsavelAvaliacaoRouteImport.update({
    id: '/avaliacao',
    path: '/avaliacao',
    getParentRoute: () => RespResponsavelRoute,
  } as any)
const RespResponsavelInventarioRoute =
  RespResponsavelInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => RespResponsavelRoute,
  } as any)
const RespResponsavelPortariaRoute = RespResponsavelPortariaRouteImport.update({
  id: '/portaria',
  path: '/portaria',
  getParentRoute: () => RespResponsavelRoute,
} as any)
const RespResponsavelTransferenciaRoute =
  RespResponsavelTransferenciaRouteImport.update({
    id: '/transferencia',
    path: '/transferencia',
    getParentRoute: () => RespResponsavelRoute,
  } as any)
const RespResponsavelTransferenciasPendentesRoute =
  RespResponsavelTransferenciasPendentesRouteImport.update({
    id: '/transferencias-pendentes',
    path: '/transferencias-pendentes',
    getParentRoute: () => RespResponsavelRoute,
  } as any)
const RespResponsavelTrocaResponsabilidadeRoute =
  RespResponsavelTrocaResponsabilidadeRouteImport.update({
    id: '/troca-responsabilidade',
    path: '/troca-responsabilidade',
    getParentRoute: () => RespResponsavelRoute,
  } as any)
const RespResponsavelTutorialRoute = RespResponsavelTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => RespResponsavelRoute,
} as any)
const AppAdmBensCadastroRoute = AppAdmBensCadastroRouteImport.update({
  id: '/bens/cadastro',
  path: '/bens/cadastro',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmBensCategoriasRoute = AppAdmBensCategoriasRouteImport.update({
  id: '/bens/categorias',
  path: '/bens/categorias',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmContabilidadeUsuariosRoute =
  AppAdmContabilidadeUsuariosRouteImport.update({
    id: '/contabilidade/usuarios',
    path: '/contabilidade/usuarios',
    getParentRoute: () => AppAdmRoute,
  } as any)
const AppAdmFotosCanvasRoute = AppAdmFotosCanvasRouteImport.update({
  id: '/fotos/canvas',
  path: '/fotos/canvas',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmFotosCapturarRoute = AppAdmFotosCapturarRouteImport.update({
  id: '/fotos/capturar',
  path: '/fotos/capturar',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmGalpaoEmpenhosRoute = AppAdmGalpaoEmpenhosRouteImport.update({
  id: '/galpao/empenhos',
  path: '/galpao/empenhos',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmGalpaoGraficosRoute = AppAdmGalpaoGraficosRouteImport.update({
  id: '/galpao/graficos',
  path: '/galpao/graficos',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmGalpaoRetiradasRoute = AppAdmGalpaoRetiradasRouteImport.update({
  id: '/galpao/retiradas',
  path: '/galpao/retiradas',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmInventarioMerendaRoute = AppAdmInventarioMerendaRouteImport.update({
  id: '/inventario/merenda',
  path: '/inventario/merenda',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmInventarioMonitoramentoRoute =
  AppAdmInventarioMonitoramentoRouteImport.update({
    id: '/inventario/monitoramento',
    path: '/inventario/monitoramento',
    getParentRoute: () => AppAdmRoute,
  } as any)
const AppAdmInventarioTransferenciasRoute =
  AppAdmInventarioTransferenciasRouteImport.update({
    id: '/inventario/transferencias',
    path: '/inventario/transferencias',
    getParentRoute: () => AppAdmRoute,
  } as any)
const AppAdmLocaisCadastroUsuariosRoute =
  AppAdmLocaisCadastroUsuariosRouteImport.update({
    id: '/locais/cadastro-usuarios',
    path: '/locais/cadastro-usuarios',
    getParentRoute: () => AppAdmRoute,
  } as any)
const AppAdmLocaisFichasRoute = AppAdmLocaisFichasRouteImport.update({
  id: '/locais/fichas',
  path: '/locais/fichas',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmLocaisPortariaRoute = AppAdmLocaisPortariaRouteImport.update({
  id: '/locais/portaria',
  path: '/locais/portaria',
  getParentRoute: () => AppAdmRoute,
} as any)
const AppAdmGalpaoRetiradasGerenciarRoute =
  AppAdmGalpaoRetiradasGerenciarRouteImport.update({
    id: '/gerenciar',
    path: '/gerenciar',
    getParentRoute: () => AppAdmGalpaoRetiradasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/responsavel-login': typeof ResponsavelLoginRoute
  '/set-password': typeof SetPasswordRoute
  '/adm': typeof AppAdmRouteWithChildren
  '/chefia': typeof AppChefiaRoute
  '/painel-setor': typeof AppPainelSetorRoute
  '/responsavel': typeof RespResponsavelRouteWithChildren
  '/adm/auditoria': typeof AppAdmAuditoriaRoute
  '/adm/base': typeof AppAdmBaseRoute
  '/adm/buscar': typeof AppAdmBuscarRoute
  '/adm/buscas': typeof AppAdmBuscasRoute
  '/adm/configuracoes': typeof AppAdmConfiguracoesRoute
  '/adm/etiqueta': typeof AppAdmEtiquetaRoute
  '/adm/explorar': typeof AppAdmExplorarRoute
  '/adm/ia': typeof AppAdmIaRoute
  '/adm/integracoes': typeof AppAdmIntegracoesRoute
  '/adm/notificacoes': typeof AppAdmNotificacoesRoute
  '/adm/painel-emails': typeof AppAdmPainelEmailsRoute
  '/adm/relatorios': typeof AppAdmRelatoriosRoute
  '/inventario/conferencia': typeof AppInventarioConferenciaRoute
  '/inventario/lista': typeof AppInventarioListaRoute
  '/inventario/transferir': typeof AppInventarioTransferirRoute
  '/locais/bens-setor': typeof AppLocaisBensSetorRoute
  '/responsavel/avaliacao': typeof RespResponsavelAvaliacaoRoute
  '/responsavel/inventario': typeof RespResponsavelInventarioRoute
  '/responsavel/portaria': typeof RespResponsavelPortariaRoute
  '/responsavel/transferencia': typeof RespResponsavelTransferenciaRoute
  '/responsavel/transferencias-pendentes': typeof RespResponsavelTransferenciasPendentesRoute
  '/responsavel/troca-responsabilidade': typeof RespResponsavelTrocaResponsabilidadeRoute
  '/responsavel/tutorial': typeof RespResponsavelTutorialRoute
  '/adm/': typeof AppAdmIndexRoute
  '/adm/bens/cadastro': typeof AppAdmBensCadastroRoute
  '/adm/bens/categorias': typeof AppAdmBensCategoriasRoute
  '/adm/contabilidade/usuarios': typeof AppAdmContabilidadeUsuariosRoute
  '/adm/fotos/canvas': typeof AppAdmFotosCanvasRoute
  '/adm/fotos/capturar': typeof AppAdmFotosCapturarRoute
  '/adm/galpao/empenhos': typeof AppAdmGalpaoEmpenhosRoute
  '/adm/galpao/graficos': typeof AppAdmGalpaoGraficosRoute
  '/adm/galpao/retiradas': typeof AppAdmGalpaoRetiradasRouteWithChildren
  '/adm/inventario/merenda': typeof AppAdmInventarioMerendaRoute
  '/adm/inventario/monitoramento': typeof AppAdmInventarioMonitoramentoRoute
  '/adm/inventario/transferencias': typeof AppAdmInventarioTransferenciasRoute
  '/adm/locais/cadastro-usuarios': typeof AppAdmLocaisCadastroUsuariosRoute
  '/adm/locais/fichas': typeof AppAdmLocaisFichasRoute
  '/adm/locais/portaria': typeof AppAdmLocaisPortariaRoute
  '/adm/galpao/retiradas/gerenciar': typeof AppAdmGalpaoRetiradasGerenciarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/responsavel-login': typeof ResponsavelLoginRoute
  '/set-password': typeof SetPasswordRoute
  '/chefia': typeof AppChefiaRoute
  '/painel-setor': typeof AppPainelSetorRoute
  '/responsavel': typeof RespResponsavelRouteWithChildren
  '/adm/auditoria': typeof AppAdmAuditoriaRoute
  '/adm/base': typeof AppAdmBaseRoute
  '/adm/buscar': typeof AppAdmBuscarRoute
  '/adm/buscas': typeof AppAdmBuscasRoute
  '/adm/configuracoes': typeof AppAdmConfiguracoesRoute
  '/adm/etiqueta': typeof AppAdmEtiquetaRoute
  '/adm/explorar': typeof AppAdmExplorarRoute
  '/adm/ia': typeof AppAdmIaRoute
  '/adm/integracoes': typeof AppAdmIntegracoesRoute
  '/adm/notificacoes': typeof AppAdmNotificacoesRoute
  '/adm/painel-emails': typeof AppAdmPainelEmailsRoute
  '/adm/relatorios': typeof AppAdmRelatoriosRoute
  '/inventario/conferencia': typeof AppInventarioConferenciaRoute
  '/inventario/lista': typeof AppInventarioListaRoute
  '/inventario/transferir': typeof AppInventarioTransferirRoute
  '/locais/bens-setor': typeof AppLocaisBensSetorRoute
  '/responsavel/avaliacao': typeof RespResponsavelAvaliacaoRoute
  '/responsavel/inventario': typeof RespResponsavelInventarioRoute
  '/responsavel/portaria': typeof RespResponsavelPortariaRoute
  '/responsavel/transferencia': typeof RespResponsavelTransferenciaRoute
  '/responsavel/transferencias-pendentes': typeof RespResponsavelTransferenciasPendentesRoute
  '/responsavel/troca-responsabilidade': typeof RespResponsavelTrocaResponsabilidadeRoute
  '/responsavel/tutorial': typeof RespResponsavelTutorialRoute
  '/adm': typeof AppAdmIndexRoute
  '/adm/bens/cadastro': typeof AppAdmBensCadastroRoute
  '/adm/bens/categorias': typeof AppAdmBensCategoriasRoute
  '/adm/contabilidade/usuarios': typeof AppAdmContabilidadeUsuariosRoute
  '/adm/fotos/canvas': typeof AppAdmFotosCanvasRoute
  '/adm/fotos/capturar': typeof AppAdmFotosCapturarRoute
  '/adm/galpao/empenhos': typeof AppAdmGalpaoEmpenhosRoute
  '/adm/galpao/graficos': typeof AppAdmGalpaoGraficosRoute
  '/adm/galpao/retiradas': typeof AppAdmGalpaoRetiradasRouteWithChildren
  '/adm/inventario/merenda': typeof AppAdmInventarioMerendaRoute
  '/adm/inventario/monitoramento': typeof AppAdmInventarioMonitoramentoRoute
  '/adm/inventario/transferencias': typeof AppAdmInventarioTransferenciasRoute
  '/adm/locais/cadastro-usuarios': typeof AppAdmLocaisCadastroUsuariosRoute
  '/adm/locais/fichas': typeof AppAdmLocaisFichasRoute
  '/adm/locais/portaria': typeof AppAdmLocaisPortariaRoute
  '/adm/galpao/retiradas/gerenciar': typeof AppAdmGalpaoRetiradasGerenciarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_resp': typeof RespRouteWithChildren
  '/login': typeof LoginRoute
  '/responsavel-login': typeof ResponsavelLoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/adm': typeof AppAdmRouteWithChildren
  '/_app/chefia': typeof AppChefiaRoute
  '/_app/painel-setor': typeof AppPainelSetorRoute
  '/_resp/responsavel': typeof RespResponsavelRouteWithChildren
  '/_app/adm/auditoria': typeof AppAdmAuditoriaRoute
  '/_app/adm/base': typeof AppAdmBaseRoute
  '/_app/adm/buscar': typeof AppAdmBuscarRoute
  '/_app/adm/buscas': typeof AppAdmBuscasRoute
  '/_app/adm/configuracoes': typeof AppAdmConfiguracoesRoute
  '/_app/adm/etiqueta': typeof AppAdmEtiquetaRoute
  '/_app/adm/explorar': typeof AppAdmExplorarRoute
  '/_app/adm/ia': typeof AppAdmIaRoute
  '/_app/adm/integracoes': typeof AppAdmIntegracoesRoute
  '/_app/adm/notificacoes': typeof AppAdmNotificacoesRoute
  '/_app/adm/painel-emails': typeof AppAdmPainelEmailsRoute
  '/_app/adm/relatorios': typeof AppAdmRelatoriosRoute
  '/_app/inventario/conferencia': typeof AppInventarioConferenciaRoute
  '/_app/inventario/lista': typeof AppInventarioListaRoute
  '/_app/inventario/transferir': typeof AppInventarioTransferirRoute
  '/_app/locais/bens-setor': typeof AppLocaisBensSetorRoute
  '/_resp/responsavel/avaliacao': typeof RespResponsavelAvaliacaoRoute
  '/_resp/responsavel/inventario': typeof RespResponsavelInventarioRoute
  '/_resp/responsavel/portaria': typeof RespResponsavelPortariaRoute
  '/_resp/responsavel/transferencia': typeof RespResponsavelTransferenciaRoute
  '/_resp/responsavel/transferencias-pendentes': typeof RespResponsavelTransferenciasPendentesRoute
  '/_resp/responsavel/troca-responsabilidade': typeof RespResponsavelTrocaResponsabilidadeRoute
  '/_resp/responsavel/tutorial': typeof RespResponsavelTutorialRoute
  '/_app/adm/': typeof AppAdmIndexRoute
  '/_app/adm/bens/cadastro': typeof AppAdmBensCadastroRoute
  '/_app/adm/bens/categorias': typeof AppAdmBensCategoriasRoute
  '/_app/adm/contabilidade/usuarios': typeof AppAdmContabilidadeUsuariosRoute
  '/_app/adm/fotos/canvas': typeof AppAdmFotosCanvasRoute
  '/_app/adm/fotos/capturar': typeof AppAdmFotosCapturarRoute
  '/_app/adm/galpao/empenhos': typeof AppAdmGalpaoEmpenhosRoute
  '/_app/adm/galpao/graficos': typeof AppAdmGalpaoGraficosRoute
  '/_app/adm/galpao/retiradas': typeof AppAdmGalpaoRetiradasRouteWithChildren
  '/_app/adm/inventario/merenda': typeof AppAdmInventarioMerendaRoute
  '/_app/adm/inventario/monitoramento': typeof AppAdmInventarioMonitoramentoRoute
  '/_app/adm/inventario/transferencias': typeof AppAdmInventarioTransferenciasRoute
  '/_app/adm/locais/cadastro-usuarios': typeof AppAdmLocaisCadastroUsuariosRoute
  '/_app/adm/locais/fichas': typeof AppAdmLocaisFichasRoute
  '/_app/adm/locais/portaria': typeof AppAdmLocaisPortariaRoute
  '/_app/adm/galpao/retiradas/gerenciar': typeof AppAdmGalpaoRetiradasGerenciarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/responsavel-login'
    | '/set-password'
    | '/adm'
    | '/chefia'
    | '/painel-setor'
    | '/responsavel'
    | '/adm/auditoria'
    | '/adm/base'
    | '/adm/buscar'
    | '/adm/buscas'
    | '/adm/configuracoes'
    | '/adm/etiqueta'
    | '/adm/explorar'
    | '/adm/ia'
    | '/adm/integracoes'
    | '/adm/notificacoes'
    | '/adm/painel-emails'
    | '/adm/relatorios'
    | '/inventario/conferencia'
    | '/inventario/lista'
    | '/inventario/transferir'
    | '/locais/bens-setor'
    | '/responsavel/avaliacao'
    | '/responsavel/inventario'
    | '/responsavel/portaria'
    | '/responsavel/transferencia'
    | '/responsavel/transferencias-pendentes'
    | '/responsavel/troca-responsabilidade'
    | '/responsavel/tutorial'
    | '/adm/'
    | '/adm/bens/cadastro'
    | '/adm/bens/categorias'
    | '/adm/contabilidade/usuarios'
    | '/adm/fotos/canvas'
    | '/adm/fotos/capturar'
    | '/adm/galpao/empenhos'
    | '/adm/galpao/graficos'
    | '/adm/galpao/retiradas'
    | '/adm/inventario/merenda'
    | '/adm/inventario/monitoramento'
    | '/adm/inventario/transferencias'
    | '/adm/locais/cadastro-usuarios'
    | '/adm/locais/fichas'
    | '/adm/locais/portaria'
    | '/adm/galpao/retiradas/gerenciar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/responsavel-login'
    | '/set-password'
    | '/chefia'
    | '/painel-setor'
    | '/responsavel'
    | '/adm/auditoria'
    | '/adm/base'
    | '/adm/buscar'
    | '/adm/buscas'
    | '/adm/configuracoes'
    | '/adm/etiqueta'
    | '/adm/explorar'
    | '/adm/ia'
    | '/adm/integracoes'
    | '/adm/notificacoes'
    | '/adm/painel-emails'
    | '/adm/relatorios'
    | '/inventario/conferencia'
    | '/inventario/lista'
    | '/inventario/transferir'
    | '/locais/bens-setor'
    | '/responsavel/avaliacao'
    | '/responsavel/inventario'
    | '/responsavel/portaria'
    | '/responsavel/transferencia'
    | '/responsavel/transferencias-pendentes'
    | '/responsavel/troca-responsabilidade'
    | '/responsavel/tutorial'
    | '/adm'
    | '/adm/bens/cadastro'
    | '/adm/bens/categorias'
    | '/adm/contabilidade/usuarios'
    | '/adm/fotos/canvas'
    | '/adm/fotos/capturar'
    | '/adm/galpao/empenhos'
    | '/adm/galpao/graficos'
    | '/adm/galpao/retiradas'
    | '/adm/inventario/merenda'
    | '/adm/inventario/monitoramento'
    | '/adm/inventario/transferencias'
    | '/adm/locais/cadastro-usuarios'
    | '/adm/locais/fichas'
    | '/adm/locais/portaria'
    | '/adm/galpao/retiradas/gerenciar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_resp'
    | '/login'
    | '/responsavel-login'
    | '/set-password'
    | '/_app/adm'
    | '/_app/chefia'
    | '/_app/painel-setor'
    | '/_resp/responsavel'
    | '/_app/adm/auditoria'
    | '/_app/adm/base'
    | '/_app/adm/buscar'
    | '/_app/adm/buscas'
    | '/_app/adm/configuracoes'
    | '/_app/adm/etiqueta'
    | '/_app/adm/explorar'
    | '/_app/adm/ia'
    | '/_app/adm/integracoes'
    | '/_app/adm/notificacoes'
    | '/_app/adm/painel-emails'
    | '/_app/adm/relatorios'
    | '/_app/inventario/conferencia'
    | '/_app/inventario/lista'
    | '/_app/inventario/transferir'
    | '/_app/locais/bens-setor'
    | '/_resp/responsavel/avaliacao'
    | '/_resp/responsavel/inventario'
    | '/_resp/responsavel/portaria'
    | '/_resp/responsavel/transferencia'
    | '/_resp/responsavel/transferencias-pendentes'
    | '/_resp/responsavel/troca-responsabilidade'
    | '/_resp/responsavel/tutorial'
    | '/_app/adm/'
    | '/_app/adm/bens/cadastro'
    | '/_app/adm/bens/categorias'
    | '/_app/adm/contabilidade/usuarios'
    | '/_app/adm/fotos/canvas'
    | '/_app/adm/fotos/capturar'
    | '/_app/adm/galpao/empenhos'
    | '/_app/adm/galpao/graficos'
    | '/_app/adm/galpao/retiradas'
    | '/_app/adm/inventario/merenda'
    | '/_app/adm/inventario/monitoramento'
    | '/_app/adm/inventario/transferencias'
    | '/_app/adm/locais/cadastro-usuarios'
    | '/_app/adm/locais/fichas'
    | '/_app/adm/locais/portaria'
    | '/_app/adm/galpao/retiradas/gerenciar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RespRoute: typeof RespRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResponsavelLoginRoute: typeof ResponsavelLoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_resp': {
      id: '/_resp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RespRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsavel-login': {
      id: '/responsavel-login'
      path: '/responsavel-login'
      fullPath: '/responsavel-login'
      preLoaderRoute: typeof ResponsavelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/adm': {
      id: '/_app/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AppAdmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chefia': {
      id: '/_app/chefia'
      path: '/chefia'
      fullPath: '/chefia'
      preLoaderRoute: typeof AppChefiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel-setor': {
      id: '/_app/painel-setor'
      path: '/painel-setor'
      fullPath: '/painel-setor'
      preLoaderRoute: typeof AppPainelSetorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_resp/responsavel': {
      id: '/_resp/responsavel'
      path: '/responsavel'
      fullPath: '/responsavel'
      preLoaderRoute: typeof RespResponsavelRouteImport
      parentRoute: typeof RespRoute
    }
    '/_app/adm/': {
      id: '/_app/adm/'
      path: '/'
      fullPath: '/adm/'
      preLoaderRoute: typeof AppAdmIndexRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/auditoria': {
      id: '/_app/adm/auditoria'
      path: '/auditoria'
      fullPath: '/adm/auditoria'
      preLoaderRoute: typeof AppAdmAuditoriaRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/base': {
      id: '/_app/adm/base'
      path: '/base'
      fullPath: '/adm/base'
      preLoaderRoute: typeof AppAdmBaseRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/buscar': {
      id: '/_app/adm/buscar'
      path: '/buscar'
      fullPath: '/adm/buscar'
      preLoaderRoute: typeof AppAdmBuscarRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/buscas': {
      id: '/_app/adm/buscas'
      path: '/buscas'
      fullPath: '/adm/buscas'
      preLoaderRoute: typeof AppAdmBuscasRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/configuracoes': {
      id: '/_app/adm/configuracoes'
      path: '/configuracoes'
      fullPath: '/adm/configuracoes'
      preLoaderRoute: typeof AppAdmConfiguracoesRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/etiqueta': {
      id: '/_app/adm/etiqueta'
      path: '/etiqueta'
      fullPath: '/adm/etiqueta'
      preLoaderRoute: typeof AppAdmEtiquetaRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/explorar': {
      id: '/_app/adm/explorar'
      path: '/explorar'
      fullPath: '/adm/explorar'
      preLoaderRoute: typeof AppAdmExplorarRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/ia': {
      id: '/_app/adm/ia'
      path: '/ia'
      fullPath: '/adm/ia'
      preLoaderRoute: typeof AppAdmIaRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/integracoes': {
      id: '/_app/adm/integracoes'
      path: '/integracoes'
      fullPath: '/adm/integracoes'
      preLoaderRoute: typeof AppAdmIntegracoesRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/notificacoes': {
      id: '/_app/adm/notificacoes'
      path: '/notificacoes'
      fullPath: '/adm/notificacoes'
      preLoaderRoute: typeof AppAdmNotificacoesRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/painel-emails': {
      id: '/_app/adm/painel-emails'
      path: '/painel-emails'
      fullPath: '/adm/painel-emails'
      preLoaderRoute: typeof AppAdmPainelEmailsRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/relatorios': {
      id: '/_app/adm/relatorios'
      path: '/relatorios'
      fullPath: '/adm/relatorios'
      preLoaderRoute: typeof AppAdmRelatoriosRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/inventario/conferencia': {
      id: '/_app/inventario/conferencia'
      path: '/inventario/conferencia'
      fullPath: '/inventario/conferencia'
      preLoaderRoute: typeof AppInventarioConferenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario/lista': {
      id: '/_app/inventario/lista'
      path: '/inventario/lista'
      fullPath: '/inventario/lista'
      preLoaderRoute: typeof AppInventarioListaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario/transferir': {
      id: '/_app/inventario/transferir'
      path: '/inventario/transferir'
      fullPath: '/inventario/transferir'
      preLoaderRoute: typeof AppInventarioTransferirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locais/bens-setor': {
      id: '/_app/locais/bens-setor'
      path: '/locais/bens-setor'
      fullPath: '/locais/bens-setor'
      preLoaderRoute: typeof AppLocaisBensSetorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_resp/responsavel/avaliacao': {
      id: '/_resp/responsavel/avaliacao'
      path: '/avaliacao'
      fullPath: '/responsavel/avaliacao'
      preLoaderRoute: typeof RespResponsavelAvaliacaoRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_resp/responsavel/inventario': {
      id: '/_resp/responsavel/inventario'
      path: '/inventario'
      fullPath: '/responsavel/inventario'
      preLoaderRoute: typeof RespResponsavelInventarioRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_resp/responsavel/portaria': {
      id: '/_resp/responsavel/portaria'
      path: '/portaria'
      fullPath: '/responsavel/portaria'
      preLoaderRoute: typeof RespResponsavelPortariaRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_resp/responsavel/transferencia': {
      id: '/_resp/responsavel/transferencia'
      path: '/transferencia'
      fullPath: '/responsavel/transferencia'
      preLoaderRoute: typeof RespResponsavelTransferenciaRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_resp/responsavel/transferencias-pendentes': {
      id: '/_resp/responsavel/transferencias-pendentes'
      path: '/transferencias-pendentes'
      fullPath: '/responsavel/transferencias-pendentes'
      preLoaderRoute: typeof RespResponsavelTransferenciasPendentesRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_resp/responsavel/troca-responsabilidade': {
      id: '/_resp/responsavel/troca-responsabilidade'
      path: '/troca-responsabilidade'
      fullPath: '/responsavel/troca-responsabilidade'
      preLoaderRoute: typeof RespResponsavelTrocaResponsabilidadeRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_resp/responsavel/tutorial': {
      id: '/_resp/responsavel/tutorial'
      path: '/tutorial'
      fullPath: '/responsavel/tutorial'
      preLoaderRoute: typeof RespResponsavelTutorialRouteImport
      parentRoute: typeof RespResponsavelRoute
    }
    '/_app/adm/bens/cadastro': {
      id: '/_app/adm/bens/cadastro'
      path: '/bens/cadastro'
      fullPath: '/adm/bens/cadastro'
      preLoaderRoute: typeof AppAdmBensCadastroRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/bens/categorias': {
      id: '/_app/adm/bens/categorias'
      path: '/bens/categorias'
      fullPath: '/adm/bens/categorias'
      preLoaderRoute: typeof AppAdmBensCategoriasRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/contabilidade/usuarios': {
      id: '/_app/adm/contabilidade/usuarios'
      path: '/contabilidade/usuarios'
      fullPath: '/adm/contabilidade/usuarios'
      preLoaderRoute: typeof AppAdmContabilidadeUsuariosRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/fotos/canvas': {
      id: '/_app/adm/fotos/canvas'
      path: '/fotos/canvas'
      fullPath: '/adm/fotos/canvas'
      preLoaderRoute: typeof AppAdmFotosCanvasRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/fotos/capturar': {
      id: '/_app/adm/fotos/capturar'
      path: '/fotos/capturar'
      fullPath: '/adm/fotos/capturar'
      preLoaderRoute: typeof AppAdmFotosCapturarRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/galpao/empenhos': {
      id: '/_app/adm/galpao/empenhos'
      path: '/galpao/empenhos'
      fullPath: '/adm/galpao/empenhos'
      preLoaderRoute: typeof AppAdmGalpaoEmpenhosRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/galpao/graficos': {
      id: '/_app/adm/galpao/graficos'
      path: '/galpao/graficos'
      fullPath: '/adm/galpao/graficos'
      preLoaderRoute: typeof AppAdmGalpaoGraficosRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/galpao/retiradas': {
      id: '/_app/adm/galpao/retiradas'
      path: '/galpao/retiradas'
      fullPath: '/adm/galpao/retiradas'
      preLoaderRoute: typeof AppAdmGalpaoRetiradasRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/inventario/merenda': {
      id: '/_app/adm/inventario/merenda'
      path: '/inventario/merenda'
      fullPath: '/adm/inventario/merenda'
      preLoaderRoute: typeof AppAdmInventarioMerendaRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/inventario/monitoramento': {
      id: '/_app/adm/inventario/monitoramento'
      path: '/inventario/monitoramento'
      fullPath: '/adm/inventario/monitoramento'
      preLoaderRoute: typeof AppAdmInventarioMonitoramentoRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/inventario/transferencias': {
      id: '/_app/adm/inventario/transferencias'
      path: '/inventario/transferencias'
      fullPath: '/adm/inventario/transferencias'
      preLoaderRoute: typeof AppAdmInventarioTransferenciasRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/locais/cadastro-usuarios': {
      id: '/_app/adm/locais/cadastro-usuarios'
      path: '/locais/cadastro-usuarios'
      fullPath: '/adm/locais/cadastro-usuarios'
      preLoaderRoute: typeof AppAdmLocaisCadastroUsuariosRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/locais/fichas': {
      id: '/_app/adm/locais/fichas'
      path: '/locais/fichas'
      fullPath: '/adm/locais/fichas'
      preLoaderRoute: typeof AppAdmLocaisFichasRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/locais/portaria': {
      id: '/_app/adm/locais/portaria'
      path: '/locais/portaria'
      fullPath: '/adm/locais/portaria'
      preLoaderRoute: typeof AppAdmLocaisPortariaRouteImport
      parentRoute: typeof AppAdmRoute
    }
    '/_app/adm/galpao/retiradas/gerenciar': {
      id: '/_app/adm/galpao/retiradas/gerenciar'
      path: '/gerenciar'
      fullPath: '/adm/galpao/retiradas/gerenciar'
      preLoaderRoute: typeof AppAdmGalpaoRetiradasGerenciarRouteImport
      parentRoute: typeof AppAdmGalpaoRetiradasRoute
    }
  }
}

interface AppAdmGalpaoRetiradasRouteChildren {
  AppAdmGalpaoRetiradasGerenciarRoute: typeof AppAdmGalpaoRetiradasGerenciarRoute
}

const AppAdmGalpaoRetiradasRouteChildren: AppAdmGalpaoRetiradasRouteChildren = {
  AppAdmGalpaoRetiradasGerenciarRoute: AppAdmGalpaoRetiradasGerenciarRoute,
}

const AppAdmGalpaoRetiradasRouteWithChildren =
  AppAdmGalpaoRetiradasRoute._addFileChildren(
    AppAdmGalpaoRetiradasRouteChildren,
  )

interface AppAdmRouteChildren {
  AppAdmAuditoriaRoute: typeof AppAdmAuditoriaRoute
  AppAdmBaseRoute: typeof AppAdmBaseRoute
  AppAdmBuscarRoute: typeof AppAdmBuscarRoute
  AppAdmBuscasRoute: typeof AppAdmBuscasRoute
  AppAdmConfiguracoesRoute: typeof AppAdmConfiguracoesRoute
  AppAdmEtiquetaRoute: typeof AppAdmEtiquetaRoute
  AppAdmExplorarRoute: typeof AppAdmExplorarRoute
  AppAdmIaRoute: typeof AppAdmIaRoute
  AppAdmIntegracoesRoute: typeof AppAdmIntegracoesRoute
  AppAdmNotificacoesRoute: typeof AppAdmNotificacoesRoute
  AppAdmPainelEmailsRoute: typeof AppAdmPainelEmailsRoute
  AppAdmRelatoriosRoute: typeof AppAdmRelatoriosRoute
  AppAdmIndexRoute: typeof AppAdmIndexRoute
  AppAdmBensCadastroRoute: typeof AppAdmBensCadastroRoute
  AppAdmBensCategoriasRoute: typeof AppAdmBensCategoriasRoute
  AppAdmContabilidadeUsuariosRoute: typeof AppAdmContabilidadeUsuariosRoute
  AppAdmFotosCanvasRoute: typeof AppAdmFotosCanvasRoute
  AppAdmFotosCapturarRoute: typeof AppAdmFotosCapturarRoute
  AppAdmGalpaoEmpenhosRoute: typeof AppAdmGalpaoEmpenhosRoute
  AppAdmGalpaoGraficosRoute: typeof AppAdmGalpaoGraficosRoute
  AppAdmGalpaoRetiradasRoute: typeof AppAdmGalpaoRetiradasRouteWithChildren
  AppAdmInventarioMerendaRoute: typeof AppAdmInventarioMerendaRoute
  AppAdmInventarioMonitoramentoRoute: typeof AppAdmInventarioMonitoramentoRoute
  AppAdmInventarioTransferenciasRoute: typeof AppAdmInventarioTransferenciasRoute
  AppAdmLocaisCadastroUsuariosRoute: typeof AppAdmLocaisCadastroUsuariosRoute
  AppAdmLocaisFichasRoute: typeof AppAdmLocaisFichasRoute
  AppAdmLocaisPortariaRoute: typeof AppAdmLocaisPortariaRoute
}

const AppAdmRouteChildren: AppAdmRouteChildren = {
  AppAdmAuditoriaRoute: AppAdmAuditoriaRoute,
  AppAdmBaseRoute: AppAdmBaseRoute,
  AppAdmBuscarRoute: AppAdmBuscarRoute,
  AppAdmBuscasRoute: AppAdmBuscasRoute,
  AppAdmConfiguracoesRoute: AppAdmConfiguracoesRoute,
  AppAdmEtiquetaRoute: AppAdmEtiquetaRoute,
  AppAdmExplorarRoute: AppAdmExplorarRoute,
  AppAdmIaRoute: AppAdmIaRoute,
  AppAdmIntegracoesRoute: AppAdmIntegracoesRoute,
  AppAdmNotificacoesRoute: AppAdmNotificacoesRoute,
  AppAdmPainelEmailsRoute: AppAdmPainelEmailsRoute,
  AppAdmRelatoriosRoute: AppAdmRelatoriosRoute,
  AppAdmIndexRoute: AppAdmIndexRoute,
  AppAdmBensCadastroRoute: AppAdmBensCadastroRoute,
  AppAdmBensCategoriasRoute: AppAdmBensCategoriasRoute,
  AppAdmContabilidadeUsuariosRoute: AppAdmContabilidadeUsuariosRoute,
  AppAdmFotosCanvasRoute: AppAdmFotosCanvasRoute,
  AppAdmFotosCapturarRoute: AppAdmFotosCapturarRoute,
  AppAdmGalpaoEmpenhosRoute: AppAdmGalpaoEmpenhosRoute,
  AppAdmGalpaoGraficosRoute: AppAdmGalpaoGraficosRoute,
  AppAdmGalpaoRetiradasRoute: AppAdmGalpaoRetiradasRouteWithChildren,
  AppAdmInventarioMerendaRoute: AppAdmInventarioMerendaRoute,
  AppAdmInventarioMonitoramentoRoute: AppAdmInventarioMonitoramentoRoute,
  AppAdmInventarioTransferenciasRoute: AppAdmInventarioTransferenciasRoute,
  AppAdmLocaisCadastroUsuariosRoute: AppAdmLocaisCadastroUsuariosRoute,
  AppAdmLocaisFichasRoute: AppAdmLocaisFichasRoute,
  AppAdmLocaisPortariaRoute: AppAdmLocaisPortariaRoute,
}

const AppAdmRouteWithChildren =
  AppAdmRoute._addFileChildren(AppAdmRouteChildren)

interface AppRouteChildren {
  AppAdmRoute: typeof AppAdmRouteWithChildren
  AppChefiaRoute: typeof AppChefiaRoute
  AppPainelSetorRoute: typeof AppPainelSetorRoute
  AppInventarioConferenciaRoute: typeof AppInventarioConferenciaRoute
  AppInventarioListaRoute: typeof AppInventarioListaRoute
  AppInventarioTransferirRoute: typeof AppInventarioTransferirRoute
  AppLocaisBensSetorRoute: typeof AppLocaisBensSetorRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdmRoute: AppAdmRouteWithChildren,
  AppChefiaRoute: AppChefiaRoute,
  AppPainelSetorRoute: AppPainelSetorRoute,
  AppInventarioConferenciaRoute: AppInventarioConferenciaRoute,
  AppInventarioListaRoute: AppInventarioListaRoute,
  AppInventarioTransferirRoute: AppInventarioTransferirRoute,
  AppLocaisBensSetorRoute: AppLocaisBensSetorRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RespResponsavelRouteChildren {
  RespResponsavelAvaliacaoRoute: typeof RespResponsavelAvaliacaoRoute
  RespResponsavelInventarioRoute: typeof RespResponsavelInventarioRoute
  RespResponsavelPortariaRoute: typeof RespResponsavelPortariaRoute
  RespResponsavelTransferenciaRoute: typeof RespResponsavelTransferenciaRoute
  RespResponsavelTransferenciasPendentesRoute: typeof RespResponsavelTransferenciasPendentesRoute
  RespResponsavelTrocaResponsabilidadeRoute: typeof RespResponsavelTrocaResponsabilidadeRoute
  RespResponsavelTutorialRoute: typeof RespResponsavelTutorialRoute
}

const RespResponsavelRouteChildren: RespResponsavelRouteChildren = {
  RespResponsavelAvaliacaoRoute: RespResponsavelAvaliacaoRoute,
  RespResponsavelInventarioRoute: RespResponsavelInventarioRoute,
  RespResponsavelPortariaRoute: RespResponsavelPortariaRoute,
  RespResponsavelTransferenciaRoute: RespResponsavelTransferenciaRoute,
  RespResponsavelTransferenciasPendentesRoute:
    RespResponsavelTransferenciasPendentesRoute,
  RespResponsavelTrocaResponsabilidadeRoute:
    RespResponsavelTrocaResponsabilidadeRoute,
  RespResponsavelTutorialRoute: RespResponsavelTutorialRoute,
}

const RespResponsavelRouteWithChildren = RespResponsavelRoute._addFileChildren(
  RespResponsavelRouteChildren,
)

interface RespRouteChildren {
  RespResponsavelRoute: typeof RespResponsavelRouteWithChildren
}

const RespRouteChildren: RespRouteChildren = {
  RespResponsavelRoute: RespResponsavelRouteWithChildren,
}

const RespRouteWithChildren = RespRoute._addFileChildren(RespRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RespRoute: RespRouteWithChildren,
  LoginRoute: LoginRoute,
  ResponsavelLoginRoute: ResponsavelLoginRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
